spring:
  profiles:
    default: dev
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      # Evita introspección pesada al inicio
      hibernate.boot.allow_jdbc_metadata_access: false

  flyway:
    # Por defecto apagado; lo controlas con env var
    enabled: ${FLYWAY_ENABLED:false}
    locations: classpath:db/migration

logging:
  file:
    name: ${LOG_FILE:logs/app.log}
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.example.mdt: ${LOG_LEVEL_APP:DEBUG}

# MQTT: propiedades comunes (las específicas por perfil abajo)
mqtt:
  qos: ${MQTT_QOS:1}
  clean-start: ${MQTT_CLEAN_START:true}
