spring:
  flyway:
    enabled: false
    locations: classpath:db/migration
  datasource:
    hikari:
      initializationFailTimeout: 0
      connectionTimeout: 30000
      validationTimeout: 5000
    url: jdbc:mariadb://localhost:3306/mdt?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: mdt
    password: mdtpass
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate.boot.allow_jdbc_metadata_access: false
    open-in-view: false
logging:
  file:
    name: logs/app.log
  level:
    root: INFO
    com.example.mdt: DEBUG
mqtt:
  broker-url: tcp://localhost:1883
  client-id: mdt-scan-consumer
  username:
  password:
  topic-pass: mdt/pass
  topic-ack: mdt/ack
  qos: 1
  clean-start: true
  reconnect:
    check-interval-ms: 5000



backlog:
  enabled: true
  dir: data/backlog
  drain-interval-ms: 5000
  max-per-cycle: 50
